version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tokio
    versions:
    - 1.1.1
  - dependency-name: juniper_actix
    versions:
    - 0.2.3
  - dependency-name: rust-embed
    versions:
    - 5.9.0
  - dependency-name: juniper
    versions:
    - 0.15.3
  - dependency-name: serde
    versions:
    - 1.0.123
  - dependency-name: anyhow
    versions:
    - 1.0.38
  - dependency-name: bytes
    versions:
    - 1.0.1
  - dependency-name: uuid
    versions:
    - 0.8.2
  - dependency-name: rand
    versions:
    - 0.8.3
- package-ecosystem: npm
  directory: "/fixture_setup"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
