[package]
name = "taglib2-sys"
version = "0.1.0"
authors = ["Mark Drobnak <mark.drobnak@gmail.com>"]
edition = "2018"

[build-dependencies]
cmake = "0.1"
cc = "1.0"

[dependencies]
error-chain = "0.12"
mime = "0.2"
