[package]
name = "taglib2-sys"
version = "0.1.0"
authors = ["Mark Drobnak <mark.drobnak@gmail.com>"]
edition = "2018"

[build-dependencies]
cc = "1.0"
cmake = "0.1"

[dependencies]
mime = "0.3"
thiserror = "1.0"
