[package]
name = "fixture_setup"
version = "0.1.0"
authors = ["Mark Drobnak <mark.drobnak@gmail.com>", "0xcaff <martincharles07@gmail.com>"]

[dependencies]
diesel = { version = "1.0", features = ["sqlite"] }
forte_core = { path = ".." }
serde_derive = "1.0"
serde = "1.0"
toml = "0.5"
dotenv = "0.9"
error-chain = "0.12"
r2d2 = "0.8"
chrono = "0.4"
